### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by yobeatz** [Jpsy/ha-ventilation-control#1]
The link to [https://makeprojects.com/de/project/die-klassische-kwl-wird-smart](url) does not work any more. I read your report some ago and learned so much. Can you make it available again?

**Comment by Jpsy** [comment]
Unfortunately that website went down.
I will try to upload a ZIP of its content here as a replacement. When I find the time I will also create a new project descriptions on the Home Assistant community forum website.

**Comment by yobeatz** [comment]
That would be awesome, thanks in advance!

**Comment by Jpsy** [comment]
I have uploaded all files of the makeprojects.com project and a PDF dump of that original article to the repo.
For the time being that is all I can do. I plan to release a full guide in the Home Assistant community forum if time permits.
