### ISSUE TITLE
pictures of the LB1-platine

### ISSUE THREAD

**Issue by wromotion** [Jpsy/ha-ventilation-control#2]
Hello again and many thanks for sharing your project. I'm very interested how you managed zu combine the LB1 with your ESP. Could you please provide pictures which show the connection in detail? Unfortunately this "core part" is missing in the pictures section. Thank you very much in advance. -wromotion

**Comment by Jpsy** [comment]
You are so very right: Some of the core pics of the project were missing!
I have added them now and took the opportunity to reorganize the whole img folder. It should be much easier now to find what you need.
Enjoy!

**Comment by wromotion** [comment]
Jpsy, all parts are already ordered now. Thank you very much. For a total beginner in esp this will be my first project. I am excited like a child on its birthday.

**Comment by Jpsy** [comment]
@wromotion: Guess, you live just "around the corner". You might wanna accept my contact request on Xing to get in direct contact.
